# This file was generated by GoReleaser. DO NOT EDIT.
cask "jumux" do
  version "0.3.1"

  on_macos do
    sha256 "8926c4b8f0a506e304bf6827f33cb5ea36d00c4fd7e4998c94e9f2941651f964"
    url "https://github.com/richardcase/jumux/releases/download/v#{version}/jumux_#{version}_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "7286b6eae8569ee55eff94c3c8394e8416687d6b6b955aa1c3559737e2c64ec2"
      url "https://github.com/richardcase/jumux/releases/download/v#{version}/jumux_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4d4fb1d8916704a0752cd6c96e7c2c276734374d7132aaf0e00b144a2b4dcacc"
      url "https://github.com/richardcase/jumux/releases/download/v#{version}/jumux_#{version}_linux_amd64.tar.gz"
    end
  end

  name "jumux"
  desc "Work on multiple features in parallel with coding agents."
  homepage "https://github.com/richardcase/jumux"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jumux"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jumux"]
    end
  end

  # No zap stanza required
end
