# This file was generated by GoReleaser. DO NOT EDIT.
cask "jumux" do
  version "0.4.0"

  on_macos do
    sha256 "311f5ba8476c5a91f3193191a6fdfd13c0430cfd73e8cddbe09a70d1679353e8"
    url "https://github.com/richardcase/jumux/releases/download/v#{version}/jumux_#{version}_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "86b52cb839f1ee97859913f18abe8c0337abc483a59582791b7d839ded58c6c8"
      url "https://github.com/richardcase/jumux/releases/download/v#{version}/jumux_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b189034f06556128a0ef1c8d02142c2fe79a2421bc4d04e9ff6cfffca9576b7d"
      url "https://github.com/richardcase/jumux/releases/download/v#{version}/jumux_#{version}_linux_amd64.tar.gz"
    end
  end

  name "jumux"
  desc "Work on multiple features in parallel with coding agents."
  homepage "https://github.com/richardcase/jumux"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jumux"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jumux"]
    end
  end

  # No zap stanza required
end
