# This file was generated by GoReleaser. DO NOT EDIT.
cask "jumux" do
  version "0.2.0"

  on_macos do
    sha256 "6ae5c6fa3c07f79c58948c65d7996915540e83d6be830ee18fe8dafe72678184"
    url "https://github.com/richardcase/jumux/releases/download/v#{version}/jumux_#{version}_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "66a9cc827b681c197162b74d826ba63aab4fda4942972aa82f622443badb8855"
      url "https://github.com/richardcase/jumux/releases/download/v#{version}/jumux_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fc57067561c01c5eb9fa5f465bff9906504d1da21075412d881a54f1fc755add"
      url "https://github.com/richardcase/jumux/releases/download/v#{version}/jumux_#{version}_linux_amd64.tar.gz"
    end
  end

  name "jumux"
  desc "Work on multiple features in parallel with coding agents."
  homepage "https://github.com/richardcase/jumux"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jumux"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jumux"]
    end
  end

  # No zap stanza required
end
