# This file was generated by GoReleaser. DO NOT EDIT.
cask "satchel" do
  version "0.11.0"

  on_macos do
    sha256 "1eb47e3887eff6f9f1d3374bb938612fe886bceaa5cd1f1e66961232249a54fa"
    url "https://github.com/richardcase/satchel/releases/download/v#{version}/satchel_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "5f241fe2e1a6189f6ce73c49945723983f39d30c66bc1706fbfdacc47d7b1ac5"
      url "https://github.com/richardcase/satchel/releases/download/v#{version}/satchel_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1875555d88243dd41d3cbcc7c394b549d005ab55a54b4a3c2c0f4083c2b39665"
      url "https://github.com/richardcase/satchel/releases/download/v#{version}/satchel_#{version}_linux_arm64.tar.gz"
    end
  end

  name "satchel"
  desc "Install, update and remove agent skills."
  homepage "https://github.com/richardcase/satchel"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "satchel"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/satchel"]
    end
  end

  # No zap stanza required

end
