# This file was generated by GoReleaser. DO NOT EDIT.
cask "skillsctl" do
  version "0.10.0"

  on_macos do
    sha256 "a25c3b5c2e6639c1f34c0e7009cff2ac8593aebc3f286d4bdcfaaa62604e84ce"
    url "https://github.com/richardcase/skillsctl/releases/download/v#{version}/skillsctl_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "a14bb8e14ad6196c286f14e544d5764c3261926ede7cd37f7da258ece57f40b9"
      url "https://github.com/richardcase/skillsctl/releases/download/v#{version}/skillsctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fd7f1f66d2c3cea4d7986a96214f6d98e4f177bdc11c2947e9f0b70be615fce6"
      url "https://github.com/richardcase/skillsctl/releases/download/v#{version}/skillsctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "skillsctl"
  desc "Install, update and remove agent skills."
  homepage "https://github.com/richardcase/skillsctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skillsctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/skillsctl"]
    end
  end

  # No zap stanza required

end
