# This file was generated by GoReleaser. DO NOT EDIT.
cask "skillsctl" do
  version "0.9.0"

  on_macos do
    sha256 "1df6887abeb13c21b607b82c0d341dfa17969aa7682c78c8d38147e82472ab79"
    url "https://github.com/richardcase/skillsctl/releases/download/v#{version}/skillsctl_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "6004d5442647c5c5bf17ffedf4b8af73e273a0497af6e5417cfa715b9d90bddf"
      url "https://github.com/richardcase/skillsctl/releases/download/v#{version}/skillsctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c2f85fe561ca6c21e87cac78203888439c3755f9cbc52160f16fff8e3938a15a"
      url "https://github.com/richardcase/skillsctl/releases/download/v#{version}/skillsctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "skillsctl"
  desc "Install, update and remove agent skills."
  homepage "https://github.com/richardcase/skillsctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skillsctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/skillsctl"]
    end
  end

  # No zap stanza required

end
