# This file was generated by GoReleaser. DO NOT EDIT.
cask "skillsctl" do
  version "0.4.0"

  on_macos do
    sha256 "fbf3901358f725b3e266757e7b124fc9ef651083e81fd4241c57bf75e49531f5"
    url "https://github.com/richardcase/skillsctl/releases/download/v#{version}/skillsctl_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "9537a3558b592bfd33a46a97ada2a941ab2db0a9cdef9df8dba037401ecc5124"
      url "https://github.com/richardcase/skillsctl/releases/download/v#{version}/skillsctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "65de4f1e13cfe20947b37ffe74425fd85e444c6bb4f95c9c9aa12a9948abed62"
      url "https://github.com/richardcase/skillsctl/releases/download/v#{version}/skillsctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "skillsctl"
  desc "Install, update and remove agent skills."
  homepage "https://github.com/richardcase/skillsctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skillsctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/skillsctl"]
    end
  end

  # No zap stanza required

end
